/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Kelas;

/**
 *
 * @author ACER
 */
public class HapusKelasMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form HapusKelasMahasiswa
     */
    public HapusKelasMahasiswa() {
        initComponents();
        setTitle("Hapus Kelas");
        //setLocationRelativeTo(null);
        setHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comboPilihKelas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabKelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Kelas  :");

        btnDelete.setText("Hapus");

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        comboPilihKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPilihKelasActionPerformed(evt);
            }
        });

        tabKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabKelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboPilihKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPilihKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPilihKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPilihKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPilihKelasActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     * @return 
     */
    public Object getBtnCancel() {
        return btnCancel;
    }
    
    public Object getBtnDelete() {
        return btnDelete;
    }
    
    public void addListener(ActionListener a) {
        btnDelete.addActionListener(a);
        btnCancel.addActionListener(a);
        comboPilihKelas.addActionListener(a);
    }
    
 public void setHeader() {
        String[] header = {"No","Kelas","Matakuliah","Dosen"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        tabKelas.setModel(model);
    }
    
    public void inputData(ArrayList<Kelas> listKelas) {
        DefaultTableModel model = (DefaultTableModel) tabKelas.getModel();
        for (int i = 0; i < listKelas.size(); i++) {
           if(listKelas.get(i).getMatakuliah()!=null) { //matakuliah ada
                if(listKelas.get(i).getDosen()!=null) { //matakuliah tidak ada, dosen ada
                    model.addRow(new String[] {(i+1)+"",listKelas.get(i).getNamaKelas(),
                        listKelas.get(i).getMatakuliah().getnamaMK(),
                        listKelas.get(i).getDosen().getNama()
                    });
                } else { //matakuliah ada, dosen tidak ada
                    model.addRow(new String[] {(i+1)+"",listKelas.get(i).getNamaKelas(),
                        listKelas.get(i).getMatakuliah().getnamaMK(),
                        ""
                    });
                }
            } else if(listKelas.get(i).getDosen()!=null) { //matakuliah tidak ada, dosen ada
                model.addRow(new String[] {(i+1)+"",listKelas.get(i).getNamaKelas(),
                        "",
                        listKelas.get(i).getDosen().getNama()
                    });
            } else { //matakul, dosen tidak ada
                model.addRow(new String[] {(i+1)+"",listKelas.get(i).getNamaKelas(),
                        "",
                        ""
                    });
            }
        }
    }
    
    public void setIsiComboBox(String namaKelas) {
        comboPilihKelas.addItem(namaKelas);
    }
    
    public String getIsiComboBox() {
        return comboPilihKelas.getSelectedItem().toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox comboPilihKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabKelas;
    // End of variables declaration//GEN-END:variables
}
